window:
  title: RuneLite
  auto_detect_inventory: true
  inventory_template: inventory_template.png
  inventory:
    x: 3482
    y: 1649
    slot_width: 67
    slot_height: 54
    cols: 4
    rows: 7
timing:
  click_herb_mean: 600
  click_herb_std: 150
  click_herb_min: 350
  click_herb_max: 1200
  bank_action_mean: 800
  bank_action_std: 200
  bank_action_min: 500
  bank_action_max: 1500
  after_bank_open: 400
  after_deposit: 300
  after_withdraw: 300
  after_bank_close: 200
mouse:
  speed_range:
  - 200
  - 400
  overshoot_chance: 0.3
  overshoot_distance:
  - 5
  - 15
  curve_variance: 0.3
click:
  position_sigma_ratio: 6
  duration_mean: 100
  duration_min: 50
  duration_max: 200
breaks:
  micro:
    interval:
    - 480
    - 900
    duration:
    - 2
    - 10
  long:
    interval:
    - 2700
    - 5400
    duration:
    - 60
    - 300
fatigue:
  onset_minutes: 30
  max_slowdown_percent: 50
  misclick_rate_start: 0.01
  misclick_rate_max: 0.05
attention:
  drift_chance: 0.03
  drift_targets:
  - name: minimap
    weight: 3
  - name: chat
    weight: 2
  - name: random
    weight: 1
vision:
  confidence_threshold: 0.55
  multi_scale: true
  scale_range:
  - 0.9
  - 1.1
  scale_steps: 3
safety:
  emergency_stop_key: f12
  max_session_hours: 4
  stats_log_interval: 60
herbs:
  grimy:
  - name: grimy_ranarr
    template: grimy_ranarr.png
  - name: grimy_toadflax
    template: grimy_toadflax.png
  - name: grimy_irit
    template: grimy_irit.png
  - name: grimy_avantoe
    template: grimy_avantoe.png
  - name: grimy_kwuarm
    template: grimy_kwuarm.png
  - name: grimy_snapdragon
    template: grimy_snapdragon.png
  - name: grimy_cadantine
    template: grimy_cadantine.png
  - name: grimy_lantadyme
    template: grimy_lantadyme.png
  - name: grimy_dwarf_weed
    template: grimy_dwarf_weed.png
  - name: grimy_torstol
    template: grimy_torstol.png
bank:
  booth_template: bank_booth.png
  chest_template: bank_chest.png
  deposit_all_template: deposit_all.png
  close_button_template: bank_close.png
  insert_button_template: bank_insert.png
  menu_button_template: bank_menu.png
  esc_chance: 0.7
